root - INFO - 2022-12-29 11:23:35,753 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-29 11:23:35,755 - Prediction successfull
root - INFO - 2022-12-29 11:24:19,375 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-29 11:24:19,377 - Prediction successfull
root - INFO - 2022-12-29 11:40:12,733 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-29 11:40:12,735 - Prediction successfull
root - INFO - 2022-12-29 11:40:30,075 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-29 11:40:30,080 - Prediction successfull
root - INFO - 2022-12-30 10:56:00,465 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-30 10:56:00,468 - Prediction successfull
root - INFO - 2022-12-30 10:56:01,922 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-30 10:56:01,924 - Prediction successfull
root - INFO - 2022-12-31 10:25:59,581 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-31 10:25:59,593 - Prediction successfull
root - INFO - 2022-12-31 10:26:18,514 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-31 10:26:18,515 - Prediction successfull
root - INFO - 2022-12-31 10:26:23,222 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-31 10:26:23,223 - Prediction successfull
root - INFO - 2022-12-31 10:26:24,005 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-31 10:26:24,007 - Prediction successfull
root - INFO - 2022-12-31 10:26:24,782 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-31 10:26:24,783 - Prediction successfull
root - INFO - 2022-12-31 10:26:25,561 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-31 10:26:25,563 - Prediction successfull
root - INFO - 2022-12-31 10:26:26,297 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-31 10:26:26,300 - Prediction successfull
root - INFO - 2022-12-31 10:26:26,895 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-31 10:26:26,896 - Prediction successfull
root - INFO - 2022-12-31 10:26:27,520 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-31 10:26:27,523 - Prediction successfull
root - INFO - 2022-12-31 10:26:27,520 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-31 10:26:27,523 - Prediction successfull
root - INFO - 2022-12-31 10:26:27,520 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-31 10:26:27,523 - Prediction successfull
root - INFO - 2022-12-31 10:26:27,520 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-31 10:26:27,523 - Prediction successfull
root - INFO - 2022-12-31 10:39:41,788 - IP: 127.0.0.1 address is allowed
root - ERROR - 2022-12-31 10:39:41,789 - Check the data passed to the API server from client
root - WARNING - 2022-12-31 10:44:14,815 - IP: 127.0.0.1 address is blocked..!!!
root - INFO - 2022-12-31 10:44:14,815 - you don't have the neccessary permission to access the API
rest_api_server - ERROR - 2022-12-31 10:44:14,816 - Exception on /model [POST]
Traceback (most recent call last):
  File "/home/arunachalamdharmaraj/Documents/training-repo/python/venv/lib/python3.10/site-packages/flask/app.py", line 1818, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/arunachalamdharmaraj/Documents/training-repo/python/venv/lib/python3.10/site-packages/flask/app.py", line 2309, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/home/arunachalamdharmaraj/Documents/training-repo/ml_prod_deploy/prod_server/./rest_api_server.py", line 33, in limit_remote_addr
    abort(403)
  File "/home/arunachalamdharmaraj/Documents/training-repo/python/venv/lib/python3.10/site-packages/flask/helpers.py", line 310, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/home/arunachalamdharmaraj/Documents/training-repo/python/venv/lib/python3.10/site-packages/werkzeug/exceptions.py", line 864, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.Forbidden: 403 Forbidden: You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arunachalamdharmaraj/Documents/training-repo/python/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arunachalamdharmaraj/Documents/training-repo/python/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arunachalamdharmaraj/Documents/training-repo/python/venv/lib/python3.10/site-packages/flask/app.py", line 1666, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/arunachalamdharmaraj/Documents/training-repo/python/venv/lib/python3.10/site-packages/flask/app.py", line 1606, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/arunachalamdharmaraj/Documents/training-repo/ml_prod_deploy/prod_server/./rest_api_server.py", line 20, in permission_error
    return render_template('403.html', error_code=403)
  File "/home/arunachalamdharmaraj/Documents/training-repo/python/venv/lib/python3.10/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/arunachalamdharmaraj/Documents/training-repo/python/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/arunachalamdharmaraj/Documents/training-repo/python/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/arunachalamdharmaraj/Documents/training-repo/python/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/arunachalamdharmaraj/Documents/training-repo/python/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/arunachalamdharmaraj/Documents/training-repo/python/venv/lib/python3.10/site-packages/flask/templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "/home/arunachalamdharmaraj/Documents/training-repo/python/venv/lib/python3.10/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 403.html
root - INFO - 2022-12-31 10:45:05,891 - IP: 127.0.0.1 address is allowed
root - ERROR - 2022-12-31 10:45:05,892 - Check the data passed to the API server from client
root - INFO - 2022-12-31 10:45:12,790 - IP: 127.0.0.1 address is allowed
root - INFO - 2022-12-31 10:45:12,792 - Prediction successfull
